app:
  env: "local"
  port: 8888
  app_name: "gin-app"
  app_url: "http://localhost"

log:
  level: 'info'
  root_dir: './logs'
  filename: 'app.log'
  format: ''
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true

mysql:
  driver: 'mysql'
  host: '127.0.0.1'
  port: 8306
  database: 'admin_go'
  username: 'root'
  password: 'root123456'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800
