app:
  env: "local"
  port: 8000
  app_name: "Addmin_Go"
  app_url: "http://localhost"

log:
  level: 'info'
  root_dir: './logs/'
  filename: 'app_logs'
  format: ''
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true

mysql:
  name: "root"
  host: "localhost"
  port: 3306
  password: "root123456"
  dbName: "admin_go"

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800
